micronaut:
  application:
    name: WeatherService
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
  http:
    services:
      weather-api:
        url: https://api.weatherapi.com
        read-timeout: 5s
  server:
    netty:
      access-logger:
        enabled: true
        log-format: common
netty:
  default:
    allocator:
      max-order: 3
weather-api:
  key: ${WEATHER_API_KEY}
